export const FETCH_MEETINGS = "FETCH_MEETINGS";
export const FETCH_MEETING = "FETCH_MEETING";
export const CREATE_STEERING = "CREATE_STEERING";
export const CHANGE_STEERING_EDIT = "CHANGE_STEERING_EDIT";
export const EDIT_STEERING = "EDIT_STEERING";
export const DELETE_STEERING = "DELETE_STEERING";
