export const FETCH_STEERING = "FETCH_STEERING";
export const CREATE_STEERING = "CREATE_STEERING";
export const CHANGE_STEERING_EDIT = "CHANGE_STEERING_EDIT";
export const EDIT_STEERING = "EDIT_STEERING";
export const DELETE_STEERING = "DELETE_STEERING";
