export const FETCH_HOMEPAGE = "FETCH_HOMEPAGE";
// export const CREATE_HOMEPAGE = "CREATE_HOMEPAGE";
export const CHANGE_EDIT = "CHANGE_EDIT";
export const EDIT_HOMEPAGE = "EDIT_HOMEPAGE";
export const DELETE_HOMEPAGE = "DELETE_HOMEPAGE";
