export const FETCH_NEWSLETTER = "FETCH_NEWSLETTER";
// export const CREATE_NEWSLETTER = "CREATE_NEWSLETTER";
export const CHANGE_NEWS_EDIT = "CHANGE_NEWS_EDIT";
export const EDIT_NEWSLETTER = "EDIT_NEWSLETTER";
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER";
